### Create a new user

POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "test@test.com",
  "password": "test"
}

### Sign in the user

POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "test3@test.com",
  "password": "test"
}

### Sign out the user
POST http://localhost:3000/auth/signout

### Get the current user
GET http://localhost:3000/auth/whoami

### Find a user by id
GET http://localhost:3000/auth/1

### Find all users by email
GET http://localhost:3000/auth?email=test@test.com

### Update a user
PATCH http://localhost:3000/auth/1
content-type: application/json

{
  "password": "444"
}

### Remove a user
DELETE http://localhost:3000/auth/6